# Generated by Django 2.2.5 on 2019-11-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
