# Generated by Django 2.2.5 on 2019-11-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'First Grading'), (2, 'Second Grading'), (3, 'Third Grading'), (4, 'Fourth Grading')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.Student')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Information.Subject')),
            ],
        ),
    ]
